apiVersion: apps/v1
#
# Create a deployment ( https://kubernetes.io/docs/concepts/workloads/controllers/deployment/ )
#
kind: Deployment
metadata:
  name: openie-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: openie
  template:
    metadata:
      labels:
        app: openie
    spec:
      containers:
      - name: openie
        image: bexi7507/worker-openie:v8
        ports:
        - containerPort: 9000
        env:
          - name: mongoDB_HOST
            value: "10.3.248.240"
          - name: RABBITMQ_HOST
            value: "10.3.244.125"          
